### PR TITLE
Ticketmaster API and appending table.

### PR DESCRIPTION
**Pull request by maxniederluecke**

### CODE REVIEW

**Review by TheRealMpchambers — CHANGES_REQUESTED** [review]
Max - this looks amazing!  We are going to be adding a few pages to this project.  index.html which will be the main page and then about us, contacts, and events.  Events will be the place we will need to put the tables.  If you can create a new file and name it events.html and put the tables in there that would be great.

**Comment by Ohassan82** [comment]
Reviewed.

**Review by Ohassan82 — APPROVED** [review]
Looks very good.

**Review by TheRealMpchambers — APPROVED** [review]

**Comment by TheRealMpchambers** [comment]
Good stuff

**Pull request merged**
